### PR TITLE
feat: Facilities

### LINKED ISSUE #50: Slaughterhouse Facility
Make a facilty which provides the player with the ability to make leather and meat products

### LINKED ISSUE #51: Stone Cutting Facility
Make a facility that allows the player to produce bricks

### LINKED ISSUE #52: Mining Facilty
Make a facility that boosts the mining capabilities of a settlement

### PR DESCRIPTION
**Pull request by Toby222**

### CODE REVIEW

**Comment by Toby222** [comment]
I don't know why it linked the slaughterhouse issue. But since that will be closed in this branch anwyays, I don't care.

**Comment by Danimineiro** [comment]
> I don't know why it linked the slaughterhouse issue. But since that will be closed in this branch anwyays, I don't care.

Pretty sure I linked the facility issues to the branch

**Comment by Danimineiro** [comment]
Imo ddafda2ebc674daa270c8070f697dd35b33fea24 should've be on it's own branch, it's kinda unrelated to the facilities and makes the review at the end more bloated

Unless this was needed atm?

**Comment by Toby222** [comment]
> Imo [ddafda2](https://github.com/Danimineiro/Empire-Rewritten/commit/ddafda2ebc674daa270c8070f697dd35b33fea24) should've be on it's own branch, it's kinda unrelated to the facilities and makes the review at the end more bloated
> 
> Unless this was needed atm?

It was needed for what I was testing at the time (uncommited).
But seeing as how both the things on the branch rn are just QOL things, how about creating a new branch at this commit and merging that first?

**Pull request merged**
